# Generated by Django 3.0.5 on 2024-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Kids', 'Kids'), ('Accessories', 'Accessories')], default='Men', max_length=11),
        ),
    ]
